### ISSUE TITLE
Don't reset date & Leaders when reinstating Approved Project status

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#111]
Correct application handling so that Project (Start) Date and assigned Leaders are not cleared does when an Approved Application is reverted to Site Assessment Complete in order to be updated in the Vetting area (e.g. update the Vetting Summary) then Status is changed back to Approved Project.

**Comment by dandahle** [comment]
Looking into this after the update-dependencies changes were tested, in addition to the Leaders and project start / end dates being reset, the Project Status is also reset to Project - Upcoming. The preferred behavior is to leave the Project Status as it was before the Application Status is changed back to Approved. During the test it was verified that the changes made in the Application were reflected in the Project Summary. The reset seems to happen when the Application Status  is reset to Approved.

**Comment by rohinadalja** [comment]
Replicate Bug: when the application status is changed to Approved Project the AVT clears the leaders and the planning dates in the Project Summary Upcoming Projects section

**Comment by dandahle** [comment]
This issue was resolved with the recent updated to the application with Rohin's fixes.
