### ISSUE TITLE
"Apply" button in main menu creates new Client record

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#112]
Apply button in black bar menu on top to create a new Client Application currently redirects to the Application link in the public Catalystnw.org website. Instead of doing this, clicking on the Apply button when logged into the AppVetting tool should create a new client record that the Vetting Agent can then fill out using the Vetting Application view. This would also solve the problem of getting back to the AppVetting tool when a Vetting agent manually enters a paper application.

**Comment by CatalystNW** [comment]
Not a problem
