### ISSUE TITLE
Add Google drive URL field to Site Assessment

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#126]
Add field to access Google Drive URL into the Site Assessment pages. This should point to / use the same field used in Project Info tab of Project Summary for an Application so that if a URL is added in the Site Assessment view then that URL link shows up in the Project Summary Drive URL and vice versa.

**Comment by ironmikesh** [comment]
Started branch SA-126 to begin working on this issue

**Comment by ironmikesh** [comment]
Finished work on this.  I upgraded the logic and user experience of adding and changing and visiting the google drive for Site Assessors.  If it is liked, then I can copy paste this for Project Manager People.

Please test that it persists between the two - initiate one from SA, and one from PM, and check to see that they are editable both directions.  I did this a bit - but it could be tested better in the development environment.

**Comment by dandahle** [comment]
QA tested in develop then pulled to master and pushed to production
