### ISSUE TITLE
Modify Notes field in Application to auto save 

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#133]
A number of notes have been lost by vetting agents by typing in the note field but moving off of the page before clicking the "Save" button. A request has been made to autosave notes as is done in Site Assessment Summary field in Site Assessment section.

**Comment by dandahle** [comment]
Hoping this will not be a lot of work for you, Mike.

**Comment by CatalystNW** [comment]
Moved to new GitHub
