### ISSUE TITLE
Make it optional to set up New Admin when creating new AVT instance

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#138]
With the .env variables and MongoDB & app set up, an new John Doe is set up as an admin every time a new instance is pulled from develop and set up. Since we don't have a way of deleting users, this can get very cumbersome, and if we do not disable the new admin users, we potentially have a big hole for people to access.

**Comment by rohinadalja** [comment]
In progress

**Comment by dandahle** [comment]
addressed with Rohin's revision of setup scripts in aws-config
