### ISSUE TITLE
Logging in with wrong account info isn't handled properly

### ISSUE THREAD

**Issue by rarafon** [dandahle/Catalyst-AppVetting#139]
Running the local server,
It leads to [ DATABASE ] Connection :: Connection response:  MongooseError [MongooseServerSelectionError]: Authentication failed.

And the error isn't handled nor is the result given back to the user

**Comment by dandahle** [comment]
This has to do with the nodejs application code connecting to the mongodb database. It was found by a member of our osu development team.

**Comment by rarafon** [comment]
I am going to close this. It was due to the .env file being changed because in the previous commits, the .env file (not .env.template) was saved under the repo so it was overwriting my .env file and I didn't notice. Thus, it was trying to access the MongoDB with the wrong credentials.
