### ISSUE TITLE
On AVT installation make optional to use stored .env files or create new

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#147]
Using curl script to pull and install application software to set up a new instance, give the installer the option to choose: 
production --> which points to folder in S3 holding the "production" .env file 
develop --> which points to folder in S3 holding the "develop" .env file 
new --> which uses the current method to "populate" .env file manually 

This will require entering the IAM credentials for access to the appropriate S3 bucket. 

This should be related to issue #138

**Comment by rohinadalja** [comment]
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html
