### ISSUE TITLE
Vetting Home view opens with collapsed lists

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#148]
Make it so the Declined/Withdrawn Applications and Approved Applications are collapsed by default. New Applications, Pending Applications and Wait List lists still load with expanded listing of all the applications with that status. Attachment is preferred view on opening:
![Vetting Home preferred view](https://user-images.githubusercontent.com/6306417/80926701-afd21380-8d4d-11ea-8b12-69afcc8a508d.JPG)

**Comment by CatalystNW** [comment]
Not a problem for now.
