### ISSUE TITLE
Add Export PDF buttons to top of Vetting Worksheet

### ISSUE THREAD

**Issue by ironmikesh** [dandahle/Catalyst-AppVetting#157]
Description:  

Users tend to open an application solely to print the PAF or Handle-It forms.  Users find it tedious to scroll to the bottom of the Vetting Worksheet for each application to do this.  Users request a similar button configuration to export the PDFs at the top of the Vetting Worksheet.

Acceptance Criteria:
Look at the top of VW for an Export PDFs button
PDF button content should be as follows
 - light blue button: "Export PDFs" - when this button is clicked, it should turn into
 - green buttons:  "Export PAF Report" and "Export Handle-It Report"
When a green button is clicked, the connected PDF is downloaded properly.
Functionality should be similar to the way it works at the bottom of VW

**Comment by ironmikesh** [comment]
# #157 Add Export PDF buttons to top of Vetting Worksheet

Branch 157 complete - not merged to develop yet:
Developer: Mike Haines

Highlights:
* Added PDF Export buttons and functionality to top of Vetting Worksheet
* Made behavior similar for top and bottom (press export at the top, the bottom shows that the files are ready to view as well)
* Refactored Button Verbiage to reflect what is happening (PDF Generation happens on Export, View happens on green PAF Report or Handle It Report button push - the export has already happened, so I removed export from the PAF/Handle It buttons)
* added post-export data change instructions (reload the page, export PDF again)
* Project View export buttons reflect same changes for cross-application continuity

Acceptance Criteria:
See highlights above, and Issue Description for more Acceptance Criteria

**Comment by dandahle** [comment]
Closed with the merge. May modify for two urls - one public and one private, but will open a new issue. Thanks Mike!
