### ISSUE TITLE
Error Adding an User Account

### ISSUE THREAD

**Issue by rarafon** [dandahle/Catalyst-AppVetting#161]
In the AWS instances and in the local server, the account won't be created or registered if the ID_Date form field is filled out. Running this on a local server gives an error in the attached screenshot of the terminal.

![fail_registering_user1](https://user-images.githubusercontent.com/11997170/83801961-d2ae5b00-a65e-11ea-8c0b-7cf4604ddf32.png)

**Comment by rarafon** [comment]
It is because the ID_Date property of UserPackage is of type Boolean. It's supposed to be type Date.

Previously, it was working because when the date was not given in the user registration form, it would be sent to the server as undefined. Presumably, the server then saved this as null and this is why user creation works when this field is left blank.

Subsequently, changing it back to Date won't affect previous application data since they all had their ID_Date set as null. Now, in the future, any new applications will work with the ID_Date if it is defined in the form, and the ID_Date of the previous applications will be able to be set to a date.

**Comment by dandahle** [comment]
Andy - can you do me a favor log into http://54.202.5.170 and confirm these changes have been implemented correctly in develop?

**Comment by rarafon** [comment]
I noticed that the files created previously used this property as a boolean so I will make changes to those as well. Luckily, this hasn't been close yet so I will provide updates to the branch.

**Comment by rarafon** [comment]
I added the pull request #169 

I tested it with my local server. I searched through all the files and found that ID_Date isn't used anywhere except for user creation.

![image](https://user-images.githubusercontent.com/11997170/83935391-117f0680-a76e-11ea-877d-03cf3e7c0435.png)

The account on the bottom was the one that I just created by running the createAdminUser.js file by typing in "node script/createAdminUser.js"

On a related note, I found out that you can have duplicate accounts with the emails being the same, which might be a bug.

**Comment by dandahle** [comment]
Now working in develop
