### ISSUE TITLE
Accessing '/partners' will crash the server

### ISSUE THREAD

**Issue by rarafon** [dandahle/Catalyst-AppVetting#164]
I tested this on an AWS instance and on my local server. If you access '/partners', it will crash Node.js. On browser, you're given a blank page.

On the local server, it will crash and Node.js will stop running entirely as seen in the screenshot. 

![partners_crash](https://user-images.githubusercontent.com/11997170/83803160-f4a8dd00-a660-11ea-96d6-a5924f669da6.png)

On the AWS instance, you can't see it crash explicitly. Instead, after you try to access this page, you will no longer be logged in the next time you try to access the URL to the instance again. 

I believe that Node.js crashes and the instance server sees that it crashes and restarts it again.

**Comment by rarafon** [comment]
I implemented the changes in pull request #165 

The server no longer crashes and partners is returned successfully as JSON data as seen in the screenshot:

![fixed_partners](https://user-images.githubusercontent.com/11997170/83805049-06d84a80-a664-11ea-8630-15107a47caa6.png)

The order of the functions being run is also now correct as seen in the next screenshot. First the partners is loaded, and then the requests is completed and sent back to the user who made this request.

![partners_server](https://user-images.githubusercontent.com/11997170/83805164-39824300-a664-11ea-965e-c7b53657c783.png)

**Comment by dandahle** [comment]
Will test #165 for resolution of this as well. Closing this and will close #165 when it completes the testing process.
