### ISSUE TITLE
Project Summary - Completed Projects sorted by date

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#170]
In the Project Summary the Completed Projects list is collapsable or expanded. When expanded it shows all the projects completed over time. We would like to be able to select all projects or projects for a given year, similar to what is done with the Vetting section for Approved Application. The date used to sort by should be Project Start Date

**Comment by rarafon** [comment]
Added ability to filter by year for completed & changed the start date display to the proper time zone.
