### ISSUE TITLE
Care Network - include Preferred Name in First Name transfer search

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#178]
The Care Network's awesome transfer function seems to only search the First Name field; however, the Preferred Name field is often used also. It would be nice to have the First Name search look in both the First Name field and the Preferred Name field.

**Comment by rarafon** [comment]
I updated it with pull request #181 so that searching by the first name will search both first name and preferred name. The Care Applicant also now has a preferred name property and it will be transferred over from the AppVetting.

**Comment by dandahle** [comment]
This issue is completed
