### ISSUE TITLE
Package-lock often conflicts

### ISSUE THREAD

**Issue by rohinadalja** [dandahle/Catalyst-AppVetting#185]
One suggestion is to remove `package-lock.json` from the project, making sure to add it to the `.gitignore` file. As part of this issue, we should also consider reverting the `minimist` changes in package.json and multiple `npm install steps from ./script/init-setup.sh` that were introduced to patch a security vulnerability. It may be possible that the package that was dependent on an old version of minimist may have an update, and we would only need to update that package version in package.json instead, and we would be able to remove the `preinstall script section` as well as the `resolutions section` from package.json after this change.

**Comment by dandahle** [comment]
Hi Rohin - yes, package-lock.json doesn’t seem to belong in the project, especially if we can delete it and it just rebuilds. I don’t know about the code structure requirements for those things, but your suggestion seems to be the right way to go. 

Also, Mike had dug into the minimist changes, but it started with the security warning in GitHub, which we don’t have any more, and continued with the npm security audit. We could try some new code without the patch code and see what the npm audit says. If that’s clean, that’s what I want to see and we’re all set. 

I have a new EC2 instance running with the develop-2020-Jul code that includes Andy’s Care Network code at 34.219.33.32 if you want to take a look. It uses all the same AWS credentials and login info as the other develop instances. 

My son and daughter-in-law decided to stay a few more days, so they are still here, but let’s still meet as planned at 6pm and we can walk through these things. 

Thank you, 

==> Dan

**Comment by dandahle** [comment]
Solved with Rohin's new set up and configuration process.
