### ISSUE TITLE
Dates do not show up in Planning Tab

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#194]
Dates entered for Project Plan Checklist show up in Safari but not in Windows Firefox/Chrome/Edge (it only shows mm/dd/yyyy, not the actual dates). Problem is likely formatting differences between Mac and Windows (Justin believes).

**Comment by bethelju** [comment]
Fixed in latest commit!

**Comment by dandahle** [comment]
Hi Justin - I saw that you pushed an update. I will test this afternoon, and if all looks good, I'll push into the master. I'll let you know either way. Thank you for doing this! ==> Dan
On 8/31/2020 12:53:08 PM, Justin Bethel <notifications@github.com> wrote:
Fixed in latest commit!

**Comment by dandahle** [comment]
solved with pull #196
