### ISSUE TITLE
Care: Server returns UTC time and this time isn't being adjusted accordingly

### ISSUE THREAD

**Issue by rarafon** [dandahle/Catalyst-AppVetting#209]
Creating this issue to leave a note for myself to fix in the future.

**Comment by rarafon** [comment]
The server saves the date in UTC and then returns it in the same format. One possibility is to use toLocaleString('en-US'); to return back a string in the correct format via the server or have the browser account for the difference.

**Comment by rarafon** [comment]
After looking at it, I believe that the time zone difference between the server (UTC) and end user (PST) is taken into account. I couldn't find any discrepancies anywhere.

**Comment by dandahle** [comment]
Hi Andy - thank you for continuing to work on this. Are you still working on the new Project Summary module? Merry Christmas! ==> Dan
On 12/23/2020 3:55:13 PM, Andy Situ <notifications@github.com> wrote:
After looking at it, I believe that the time zone difference between the server (UTC) and end user (PST) is taken into account. I couldn't find any discrepancies anywhere.

**Comment by rarafon** [comment]
Hi Dan,
I am working on the site assessment page. The assessment summary page with the different costs summary threw a wrench into things. Were you able to get feedback for the project summary? Merry Christmas as well.

**Comment by dandahle** [comment]
Hi Andy - good to hear that you are working on the Site Assessment page. Did you see the email I sent with the Excel mock up of how the Darrell would like the costs to work. I ran that by him and he approved of that. I have my granddaughter with us this week, but I will work on getting feedback on the Project Summary this week. Let me know if you have questions or I can help. Thank you, 

==> Dan
On 12/24/2020 10:31:16 AM, Andy Situ <notifications@github.com> wrote:
Hi Dan,
I am working on the site assessment page. The assessment summary page with the different costs summary threw a wrench into things. Were you able to get feedback for the project summary? Merry Christmas as well.

**Comment by dandahle** [comment]
Hi Andy - the project planning team is busy with their holiday activities this week and the Catalyst office is closed. However, they meet next Tuesday and will discuss any desired changes to the Project Summary. I’ll get their input to you after that. What is the best way to get that to you? Email to your gmail account, through GitHub? 

If you want to talk through or have any questions about the the assessment summary and how the costs come together, let me know. 

I hope your holiday season is going well. Thank you for all your work on this! 

==> Dan

**Comment by rarafon** [comment]
Hi Dan,
Email works. I will be sending you an email shortly about the assessment. Thanks!
