### ISSUE TITLE
' mark generates &#x27;

### ISSUE THREAD

**Issue by CatalystNW** [dandahle/Catalyst-AppVetting#218]
When using the ' mark in the name and address field, it stores &#x27; instead.  I have confirmed it with on two separate applications.  Attaching screen shots here.
![Name characters](https://user-images.githubusercontent.com/80135909/112090898-9ac2c680-8b51-11eb-81eb-a3d6560c0216.PNG)
![Confirmed](https://user-images.githubusercontent.com/80135909/112090901-9b5b5d00-8b51-11eb-86c2-ffa3af668da4.PNG)

**Comment by dandahle** [comment]
Early on we tested fields for robust entry. We had some issues with special characters being used and then interpreted by MongoDB as database commands. I don't recall if we decided apostrophes were OK or not. We should check with Mike Haines to see if he remembers.
