### ISSUE TITLE
Application signature and Date unseen in new application review page

### ISSUE THREAD

**Issue by JJMilmore** [dandahle/Catalyst-AppVetting#219]
I submitted an application and signed it with a false name and chose a date that was in the future.   The submission was accepted.  When reviewing the new application, I was unable to locate a place to see the signature or the date signed to verify the false date or name.

**Comment by rarafon** [comment]
I added this in the recent commit and it'll appear at the bottom as:

![image](https://user-images.githubusercontent.com/11997170/112736558-d7573f00-8f10-11eb-90c5-c6624d8065f7.png)

**Comment by rarafon** [comment]
Closing issue, but this can be reopened or a new one created if further changes are needed. This was a quick and simple fix.
