### ISSUE TITLE
Move Checklist tab to left on Site Assessment working page

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#221]
This request is for the page after you click on an Application in the Assessments view. 

The Checklist tab has control for the Site Assessment status, Assessment summary, etc. so the tab should be all the way on the left and the default landing tab (instead of Work Items) when navigating by clicking on an Application.  

Order of tabs can be "Checklist" | "Work Items" | "Cost Summary" | "Partners"

**Comment by rarafon** [comment]
Implemented in the newest commit on branch project-manager.
