### ISSUE TITLE
Add “Pending” status for Work Items in Site Assessment

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#222]
Site Assessment menu: Application view: Work Items tab
Add “Pending” status for Work Items in Site Assessment 
Have Work Items with "Pending" status show up in Cost Summary (as well as "Accepted" Work Items) 

"Pending" Work Items go into the PAF for approval request. After PAF is approved ("Project Approved" status), change status for Work Items approved in the PAF from "Pending" to "Accepted".

**Comment by rarafon** [comment]
Right now there is already a "To Review" status for the assessment work items that also shows up in the Cost Summary and PAF.

Side note: I didn't notice that the PAF also includes declined work items but I should change the momentarily.

Is the difference the fact that it'll be automatically be set to approved when the assessment status is changed to "Project Approved"?

**Comment by dandahle** [comment]
Hi Andy - Here's how I see the process working, and why I've asked for a fourth state for Status for Work Items in Assessments: 

To Review == Work Item is to be reviewed / evaluated at the site assessment and a decision made to either Recommend (aka Pending) or Decline for Project Approval step (where the approval is determined by the executive director and the board). 

Pending (or Recommended?) == Work Item is recommended for approval by the ED / Board to be included in the proposed project. 

Accepted == ED / Board approve the Work Items as part of a project to be done by Catalyst 

Declined == Work Item has been declined by the site assessment agent and / or the ED / Board

Does this make sense to you?

**Comment by rarafon** [comment]
Pending status is added, and the pending work items will be set to approved when the project is approved. The page is reloaded as a quick fix to reset to work items status due to the implementation of the React elements and not using React Redux.
