### ISSUE TITLE
Managing Work Items in Site Assessment

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#223]
Sometimes there can be many Work Items to review at a Site Assessment. In order to ensure all Work Items are addressed during the Site Assessment at the applicant's property, either 

a) sort the Work Items in the Work Items tab so that the "To Review" status are at the top of the list, or 
b) in the Checklist tab add a list of "To Review" Work Items with links to them to make them easy to find for evaluation.

**Comment by rarafon** [comment]
From newest commits, the work items in the assessment and project pages are started by their status.
