### ISSUE TITLE
Projects: Coordinate Cost Summary with Items in Handle-It Work Item 

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#225]
The Handle-It Work Items with Items listed with costs should show up in the Cost Summary. Totaling Volunteer hours there would be nice along with number of volunteers.

**Comment by rarafon** [comment]
I fixed it so that Cost Summary for projects will show all work items in the "Project Work Items" category. Should be working now in the newest commit.
