### ISSUE TITLE
Make scroll bar clear for Work Items in Vetting Worksheet

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#227]
The enlarged window for Work Items is helpful, but it's still not obvious how to scroll to navigate other non-visible Work Items. Suggestion to make this more clear is make the scroll bar on the right persistent so it's obvious to go there to scroll and there is a visual clue as to whether the user is near the top or bottom of the scrolling field.

**Comment by rarafon** [comment]
The scrollbar is persistent if there if there are work items to be scrolled, meaning it takes more than 1 page in length. If it doesn't, then the scrollbar won't appear.

And the scrollbar provides the visual clue.

Could you provide a screenshot of the issue?

**Comment by dandahle** [comment]
I checked this on my Win10 machine and found that the scroll bar is indeed persistent there, but my original observation was on a Mac, so maybe there is some Handlebars issue? 
<img width="1376" alt="Screenshot #227-Mac-1" src="https://user-images.githubusercontent.com/6306417/112696834-c987b800-8e43-11eb-9683-517b38cbd509.png">

**Comment by rarafon** [comment]
Hopefully the recent commit will fix this issue.

**Comment by dandahle** [comment]
Yes, it does. Thank you!
