### ISSUE TITLE
Enable saving Notes in Vetting Worksheet

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#228]
<img width="1376" alt="Screenshot #228-Mac-1" src="https://user-images.githubusercontent.com/6306417/112696658-7d3c7800-8e43-11eb-83b8-aee0c1f3911b.png">
<img width="1376" alt="Screenshot #228-Mac-2" src="https://user-images.githubusercontent.com/6306417/112696689-89283a00-8e43-11eb-8c85-d5d153b2ca60.png">

In the Vetting Worksheet view, I tried to enter a note at the top but got an error message saying "Note did not save. Please try again."

**Comment by dandahle** [comment]
This functionality works properly in the production code, so there is something that the code doesn't like in the new code.

**Comment by rarafon** [comment]
Finally figured it out. I disabled the user data and had its restoration at the bottom of the todo list. It should be working now.

**Comment by dandahle** [comment]
excellent, Andy! thank you :-) ==> Dan
