### ISSUE TITLE
Allow Project Comments entry or delete in Handle-It Work Items

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#229]
Work Items in Handle-It show Project Comments; however, these would be added in the Project menu's Handle-It projects. Either enable for comments (which may be useful on occasion) or delete and save the display real estate.

**Comment by rarafon** [comment]
Do you mean allow adding and editing project comments from the vetting worksheet? In the vetting worksheet, it would create and edit the vetting comments.

The assessment comments is disabled for handle it work items from the newest commit.

**Comment by dandahle** [comment]
Must have been too late when I was testing and noting this "issue". I discovered the "Edit" button in the Work Item view in projects and can add comments as expected. No changes are requested.
