### ISSUE TITLE
VW-23 - Script Toggle (and floating buttons)

### ISSUE THREAD

**Issue by ironmikesh** [dandahle/Catalyst-AppVetting#23]
Vetting Worksheet:
Once a vetting agent has had the initial phone call, further communication with the client may be necessary, where they don't need the Phone Script (which is mostly in purple).

To facilitate this, we request that the current buttons at the top of the Vetting Worksheet float persistently underneath the Vetting Notes input.  Then add another floating button that toggles the purple script on and off.  

Please do not use the class that turns the script purple to accomplish this.  There are/will be other sections that should toggle on and off in the future.

**Acceptance Criteria**
* 4 buttons stay on the screen just under the vetting notes (as close as possible)
* The last of the 4 buttons toggle the purple sections of the script on and off.

**Comment by ironmikesh** [comment]
Work in Process 04-22-2018

**Comment by dandahle** [comment]
As of July 26th, this doesn't seem to be in the working code. Did it get stuck in the VW-23 branch?
