### ISSUE TITLE
John Jones application has mutiple Work Items in Assessment but only one Handle-It in Project

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#231]
All the Work Items are Accepted, the Checklist appears to be filled out, although the Porta Potty and Waste/Dump Trailer boxes are not ticked, but when the Assessment status is changed to Complete the Application is still in Pending and when the Application is opened it still shows Pending. When attempting to change to Project Approval a dialog box shows up with "The Assessment must first be completed!" but it's not clear what still needs to be completed on the Assessment.

**Comment by rarafon** [comment]
This was intentional. It means that the assessment status must first be set to "complete" thus the message. So it has to go from pending -> complete and then either project approval or project approved.

I can set it so that it will skip the check. I thought that it would prevent steps from being skipped.

**Comment by dandahle** [comment]
I think the checking with interlock is good. It's just I couldn't tell what was still missing / needed to do. The error message didn't give me any pointers. Maybe we should talk before you take action here?

**Comment by dandahle** [comment]
Changed title to reflect issue. First screenshot is changing from Pending to Complete. Second screenshot shows no change in Assessment status buckets. Third screenshot shows still Pending. Fourth screenshot shows error dialogue box, with no guidance on what to fix. If there was someplace to search for or the application showed a red highlight on field with missing info this would be useful. 
![Screenshot #231-Win10-1](https://user-images.githubusercontent.com/6306417/112698537-19b44980-8e47-11eb-9df3-ac5eb622914d.jpg)
![Screenshot #231-Win10-2](https://user-images.githubusercontent.com/6306417/112698539-1a4ce000-8e47-11eb-8123-b4e7521cdb2c.jpg)
![Screenshot #231-Win10-3](https://user-images.githubusercontent.com/6306417/112698540-1a4ce000-8e47-11eb-870f-bf33018f9c2f.jpg)
![Screenshot #231-Win10-4](https://user-images.githubusercontent.com/6306417/112698541-1ae57680-8e47-11eb-81cb-2d329045f3f6.jpg)



Adding screenshots

**Comment by rarafon** [comment]
Good catch. I missed calling the _id variable to check for the documents. It validates that the assessments' and application's statuses, but a line missed using the id variable. It should be fixed now.

**Comment by dandahle** [comment]
John Jones Site Assessment now shows complete.
