### ISSUE TITLE
Item Price and Cost Summary total truncates or rounds to two decimal places

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#232]
All monetary amounts should reflect dollars and cents. Volunteer hours, etc. need not be more than one decimal place.

**Comment by rarafon** [comment]
I believe that I changed all of the inputs & values to have the proper decimal places.

**Comment by dandahle** [comment]
Hi Andy - looks better, but the Cost Summary in Assessment shows integers in Price and Total for each line item as well as Project Total. Would be nice to show those with $dd.cc format. I'm still checking other areas.

**Comment by rarafon** [comment]
Should be fixed in the newer commit.

**Comment by dandahle** [comment]
Still something going on here... 
![Screenshot #232-Win10-1](https://user-images.githubusercontent.com/6306417/113441096-7e6d2800-93a2-11eb-8d1b-8f3273f331cb.jpg)
![Screenshot #232-Win10-2](https://user-images.githubusercontent.com/6306417/113441396-179c3e80-93a3-11eb-8775-edd5edc020a4.jpg)

**Comment by dandahle** [comment]
Also, notice the total line at bottom doesn't line up with the Total column in some cases. Attached are Windows screenshots.

**Comment by dandahle** [comment]
And here is a Mac screenshot. 
<img width="1133" alt="#232-Mac-1" src="https://user-images.githubusercontent.com/6306417/113441603-69dd5f80-93a3-11eb-8cc4-a83cb69e2090.png">

**Comment by rarafon** [comment]
I believe you didn't force refresh your pages so it was using the older js file. For windows, this could be done by pressing ctrl + F5.

The positioning should also be fixed in the recent commit.

**Comment by dandahle** [comment]
I'm seeing the two decimal places now, but only for numbers that are not integers, and the columns are left justified. If its easy it would be nice for all prices to have two digits showing, e.g. a "10" inputted in a price field will be shown as 10.00 or $10.00 right justified. 

However, although we'd like this is not a high priority.

**Comment by rarafon** [comment]
The price wasn't fixed previously since I wanted to make sure that the users won't be able to input any values with greater than 2 significant figures. It is fixed now.

**Comment by dandahle** [comment]
Looks good
