### ISSUE TITLE
Assessment - Make "Modify Partners" button look like a button

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#233]
in Assessment for a Site Assessment the "Modify Partners" just shows text so it's not apparent that it is a button. Please format it to look like a button to match it's action. :-)

**Comment by rarafon** [comment]
Done in a recent commit

**Comment by dandahle** [comment]
The button fill in shows up on Mac but not on Windows. I just did a code pull this morning, so I think I'm using your latest. It may be that the fill color in Win-10 is white so it looks like the background. 

Same issue for Submit, Cancel and Create Partner buttons when Modify Partners is clicked in Win-10. 

Maybe adding a button outline and using a color instead of gray would help?

**Comment by dandahle** [comment]
See previous comment w/ screenshot

**Comment by rarafon** [comment]
Previously you only mentioned the "Modify Partner" button so I didn't include that menu. Those buttons should now show up. It might require a new refresh of the page (Ctrl + F5)

**Comment by dandahle** [comment]
Beautiful! :-)
