### ISSUE TITLE
Assessment - Cost Summary tab to show # Work Items in Review

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#234]
# Work Items works as expected when at least one Work Item is moved to Accepted, however, with all Work Items in To Review status, the totals are not done, although the Volunteer total for Project Work Items in Review is correct.

**Comment by rarafon** [comment]
Good catch. This was due to forgetting to change the variable name when I c + v code in a recent commit to display the review work items. Should be fixed in the recent commit.
