### ISSUE TITLE
Vetting Worksheet - Make "Current Work Items" header persistent

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#235]
When scrolling to see all the Work Items the title "Current Work Items" scrolls out of view. To make it easier to know where the user is in the VW move Current Work Items above scroll box so it is persistent. 

Same for "Complete Work Items" (and change to "Complete**d** Work Items" (past tense))

**Comment by rarafon** [comment]
Changes are implemented.
