### ISSUE TITLE
VW - Move Declined Work Items to scroll box below Completed Work Items 

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#236]
In the Vetting Worksheet right now the Declined Work Items are shown in the Current Work Item scroll box. We would like the Current Work Items scroll box to only include Work Items to be dispositioned.

**Comment by rarafon** [comment]
Forgot to comment from changes previously. I changed it so that declined work items won't show in the vetting worksheets. This now includes the completed work items section as well in a recent commit.

**Comment by dandahle** [comment]
We do want to see the declined work items in the vetting worksheet, but in a separate place from the current Work Items and Completed Work Items. 

In the Vetting Worksheet is where we track new requests after a project or handle-it is completed, and we need to know if a work item has been requested earlier and declined so know to ask for how the situation is different or we don't go through the effort again to evaluate it.

**Comment by rarafon** [comment]
A separate container was added for the declined work items in the vetting worksheet page in the recent commit.

**Comment by rarafon** [comment]
Should the editing function be disabled?

**Comment by dandahle** [comment]
The new bucket is what I was looking for. Regarding disabling the editing function, let's wait and see how it works with the user testing. If there is a request or whatever to be able to edit a Completed or Withdrawn , we can create a new Issue and track its implementation.
