### ISSUE TITLE
VW - Move Handle-It Work Items to Completed scroll box

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#237]
In Vetting Worksheet Handle-It Work Items are shown in the Current Work Items scroll box,; however, Handle-It Work Items are dispositioned to Projects, so they should move into the Completed Work Items scroll box. We would like the Current Work Items scroll box to only include Work Items to be dispositioned.

**Comment by rarafon** [comment]
This was changed recently in a recent commit. The handle-it work items will go to the completed work items container.
