### ISSUE TITLE
Assessment - Freddy T Mercury Cost Summary 

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#238]
Cost Summary shows 1 Work Item Accepted and 1 Work Item in Review, even though there is only one Work Item showing and the Site Assessment was able to be marked Complete.

**Comment by rarafon** [comment]
I believe I saw this in the doc and I mentioned it there. It may have to do with how work items were previously created for the site assessment for all work items included handle-it ones, but I am now seeing one work item in the cost summary in the assessment page for Freddy Mercury.

**Comment by dandahle** [comment]
OK, now I'm seeing that too.
