### ISSUE TITLE
Assessment page disappeared when John Jones moved to Project Approval

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#239]
I just promoted John Jones to Project Approval and now when I click the Assessment tab nothing shows up! 
![Screenshot #239-Win10-1](https://user-images.githubusercontent.com/6306417/113442333-b5443d80-93a4-11eb-96a6-46a959fc2235.jpg)

**Comment by rarafon** [comment]
This was due to a typo. I inserted the new function name instead of replacing it. It should be fixed now in the recent commit.

**Comment by dandahle** [comment]
Thanks, Andy!
