### ISSUE TITLE
Show Handle-It and Project for Completed work items in Projects tab

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#242]
We need to be able to easily see which projects completed were Handle-Its and which were full blown Projects. If they are going to be in the same Completed bucket displayed in the Projects tab page, then a column or other designation needs to be added/created to show the two classes. 

When the Reports function is updated Projects and Handle-Its will also need to be totaled separately for year end reporting.

**Comment by rarafon** [comment]
I added a handle-it column to the view projects page with a checkmark for the ones that are handle-it for all categories. I can remove it from the sections other than the completed if it's not needed there.

**Comment by dandahle** [comment]
The Handle-It column with checkbox works for the Completed and Withdrawn sections because there is no other indication for the project type. (First screenshot) 

The Handle-It column for the working sections is not needed because "Handle-It" or "Project" is in the title of the section. (Second screenshot.) 
![Screenshot #242-Win10-1](https://user-images.githubusercontent.com/6306417/114286784-b0bbfc80-9a16-11eb-8f9b-a5d165c9d180.jpg)
![Screenshot #242-Win10-2](https://user-images.githubusercontent.com/6306417/114286786-b6194700-9a16-11eb-919d-e01a7461ed31.jpg)

**Comment by rarafon** [comment]
Yes, I am aware of that. Handleit column is now present only for the completed and withdrawn sections.
