### ISSUE TITLE
Assessment - PAF Report does not show Vetting Summary content & add Assessment Summary

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#243]
For John Jones Assessment in Project Approval when clicking the PAF report the report is generated but content for the Vetting Summary is not included. 

Also, the Assessment Summary needs to be included in the PAF in a format similar to the Vetting Summary, e.g. header with text body following.

**Comment by rarafon** [comment]
Assessment summary & vetting summary should be showing properly on the PAF report now.
