### ISSUE TITLE
Project view page - hour drop down needs to be 1-12 

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#244]
Win10 & Mac drop down shows 00 - 11 for the  hours in the schedule tool. Need to have 1 - 12 to allow selection for 12 noon. 

This is an issue in Assessment, too.

**Comment by rarafon** [comment]
Took a bit of figuring out since the 0-11 format worked with how JavaScript formats the time, but the recent commit changed it to the 1-12 format and it should be working properly.
