### ISSUE TITLE
Project View navigation - add Project Title to Client name on right

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#246]
It's a little hard to know where you are on the Projects. With client's being able to have multiple projects in this upgrade, it will be helpful to include the Project Name in the Project view.

**Comment by rarafon** [comment]
I implemented something like this: 

![image](https://user-images.githubusercontent.com/11997170/114284704-b6114b00-9a06-11eb-8c1c-9ba24214c1bc.png)

Is that what you had in mind?

**Comment by dandahle** [comment]
Yes, that works! The Project title is persistent across the tabs selected as is the client info. It's actually a better place than what I suggested. :-)
