### ISSUE TITLE
Project view - scale window for checklist when browser window is scaled larger or smaller

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#247]
The scrolling window for the Planning and WrapUp checklists seems to be fixed so that even when the browser window is made larger / longer the scrolling window stays the same size. It would be nice if the scrolling checklist window scaled vertically with the browser window.

**Comment by rarafon** [comment]
The window's height was set upon page loading, but now it will resizing when the user changes the browser height.
