### ISSUE TITLE
Project Notes not saving - HoArm project

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#249]
![Screenshot #249-Win10-1](https://user-images.githubusercontent.com/6306417/114220833-568d3f80-9921-11eb-998c-38db376b6e9a.jpg)
We updated the Handle-It project and added a second note after making the Handle-It "Completed". 

If this is because the Handle-It project was locked, 

1) a notice needs to be made to user, 

or 

2) unlock notes so they can be updated after completion. (preferred)

**Comment by dandahle** [comment]
Reviewed the regular project and after it is complete Notes can be added, so please make Handle-It behavior the same (option 2 in original comment). Thanks!

**Comment by rarafon** [comment]
Updating, adding, and deleting notes were disabled for all projects previously once completed. Updating and adding project notes is now enabled even for completed notes in the recent commit.
