### ISSUE TITLE
Ability to change Work Item in Vetting from project to Handle-It

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#250]
WE MAY NEED TO TALK ABOUT THIS... 

In the Vetting Worksheet we created a Work Item as a regular project to review in an assessment, but later determined it should be a Handle-It. It would be nice to change it's status. 

HOWEVER, if that's difficult we can create a new Handle-It Work Item and decline/delete the existing Work Item.

**Comment by rarafon** [comment]
It's harder to implement now with the change that made handle-it work items go straight to the project stage.

Implementing this might introduce more bugs, so I believe that it's best to create a new work item and deleting the existing one for now and implement this later after defining some things.

**Comment by dandahle** [comment]
Yes, I thought that might be the case that its harder now and could introduce more bugs. 

Let's leave this alone for now. I'll leave the issue open so we can track until we determine if the work around is OK or more should be done.

**Comment by dandahle** [comment]
Need to test the work around mentioned above. If that works OK for people we will close this Issue.

**Comment by dandahle** [comment]
We will use the work around of deleting the Work Item and creating a new Handle-It work item. No changes needed here.
