### ISSUE TITLE
Project Planning and WrapUp checklists

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#251]
In Planning and WrapUp tabs add label "Complete" at the top of checkbox column 

Extra credit: require all checkboxes ticked in the Planning tab before the project can be moved to “In Progress” and all the WrapUp checkboxes ticked in order to move the project to “Complete” status. If not all boxes are ticked at time of status change, and appropriate dialog box pops up to direct the to the appropriate tab to complete the checklist.

**Comment by rarafon** [comment]
Is this complete another category to check off or is it essentially a complete all button for the checklist?

**Comment by dandahle** [comment]
The checkboxes will be used to tick off items when they are complete. A ticked checkbox and Unassigned means that item is not needed. Having a column title above the checkboxes would make this more clear. 

The extra credit would be to not allow status change to In Progress unless all the Planning tab checkboxes are ticked, and not allow change to Complete without all the WrapUp checkboxes ticked.

**Comment by CatalystNW** [comment]
Closed.  Can open later if need arises.
