### ISSUE TITLE
Waste & porta potty cost

### ISSUE THREAD

**Issue by rarafon** [dandahle/Catalyst-AppVetting#252]
Right now the Assessment pages show the Porta Potty & Waste cost:

![image](https://user-images.githubusercontent.com/11997170/114424154-b1ff3d80-9b6c-11eb-8e69-9ed1044a532d.png)

But the project pages do not. 

The project pages should have this feature, right? Just wanted to make sure that it wasn't changed to somewhere else, and I forgot about it.

**Comment by dandahle** [comment]
Hi Andy - Yes, the Assessment and Project Pages should match the contents. WE originally thought that we could add those as Work Items to the project to help not make things quite so complicated for you. But, since you already have them, I think it is good to break them out like you have to be sure their planning is not messed up.

**Comment by dandahle** [comment]
If these are left separate from Work Items, their costs still need to be added to the Project Cost totals in Assessment and Project.

**Comment by dandahle** [comment]
Hi Andy - Let's make this easy (I hope). Remove the Costs for Porta Potty and Waste / Dump Trailer items on the checklist. The Check boxes should be checked to go to Project Approval. The costs for these will be accounted for as Work Items with materials details for number of rental days and daily or total costs as needed for the project.

**Comment by rarafon** [comment]
I have included the costs into project as well as their own separate costs like the site assessment. Otherwise, you wouldn't be able to find these costs for the cost summary & paf pages. It's also included into cost summary and the paf page if they're checked as required.

**Comment by dandahle** [comment]
OK Andy. How you have it is how Shawn wants it. :-)
