### ISSUE TITLE
Adding Work Items in Assessment with Project Approval status

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#255]
Don Jones assessment: changed status to Project Approval then added two Work Items. 

Approved "another something extra" Work item and it showed up in Transfer window and was assigned project. 

Declined "add'l work item 1" and it showed up in the Projects view without a project. 

Also, in the Don Jones application, the Work Items show up both in Current and in Completed and Declined. They should be in only one place there. 

Once Assessment reaches "Project Approved" adding or changing Work Items should be locked out.

**Comment by rarafon** [comment]
Removed the edit/add/remove work item buttons when the assessment has a status of approved. Didn't change the materials items buttons as it wasn't specified, but this can be done as I was in the midst of doing so. Will close, but can make further modifications if reopened.

This is getting close to what I had previously which was to disable modifications after it was complete.
