### ISSUE TITLE
Update / enable Reports and Search for new project files

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#257]
The Reports tool is critical for Shawn's end of year summary and resource planning. The way it's laid out now is exactly how Shawn wants it to be, so adding the new project data to be presented in that format is the goal. If that has to be a separate reporting system, it would be acceptable to have a "legacy reports" button for previous years project info. 

Similarly, the ability to search for a name or project across applications and projects has become an essential everyday tool for using the tool. It needs to be able to search and provide pointers to new project data, as well as old. This doesn't have to be seamless as long as a link is provided for easy navigation to the target info. 

We need to have this capability before we can release the new tool (AVT2.0) into production.

**Comment by dandahle** [comment]
This looks good to me, Andy. I'm going to have Shawn take a look to make sure he's got what he needs. No work on this needed unless we hear requests back from Shawn. After that we'll close this.

**Comment by dandahle** [comment]
Feedback from Shawn:
* CSV files are awesome! 
* Change "Upcoming Projects" tab title to "Current Projects" and include both "upcoming" and "in progress" status projects

* In "Current Projects" change "Volunteers" heading to "Volunteers Needed"
*  In "Current Projects" change "Cost" heading to "Estimated Cost"

* Change "Projects" tab title to "Completed Projects" 
* Partners list - is there a way to click a link to show the projects the Partner worked on?

for both "Current Projects" and "Completed Projects" 
* sort list by Start Date
* swap headings "Name" and "Status" to match column content

**Comment by dandahle** [comment]
Hi Andy - these changes are important to Shawn. It would be great if you could work on this next and we can put the Reports module to bed. Thank you! ==> Dan

**Comment by rarafon** [comment]
These changes were implemented in the recent commits.

**Comment by dandahle** [comment]
Hi Andy - thanks for the changes you made. This issue kinda got long and I overloaded it, so I'm going to close it and open up a couple new issues with some specific requests for edits / corrections that I noticed today when I looked at it.
