### ISSUE TITLE
PAF Report - Add Letterhead

### ISSUE THREAD

**Issue by JJMilmore** [dandahle/Catalyst-AppVetting#258]
Shawn would like the Letterhead that is on the Handle-It Report (very top) to also be used at the top of the PAF Report.

![PAF - No Letterhead](https://user-images.githubusercontent.com/80135909/115974446-aa974700-a511-11eb-90db-9b85953526ce.png)
![Handle It - Letterhead](https://user-images.githubusercontent.com/80135909/115974448-abc87400-a511-11eb-8175-d694d0aa35b1.png)

**Comment by JJMilmore** [comment]
This would include the Logo and all of the text to the right of the logo (Name, moto, address, etc..).  Place it above "Catalyst Partnerships - Project Assessment Form"

**Comment by rarafon** [comment]
Implemented in recent commit.
