### ISSUE TITLE
Assessments - change status menu text

### ISSUE THREAD

**Issue by JJMilmore** [dandahle/Catalyst-AppVetting#259]
Under the Assessments tab, please change the status drop down text line from "Project Approval" to "Awaiting Project Approval".  This will help users differential better between "Project Approval" and "Project Approved".

![Project Approval](https://user-images.githubusercontent.com/80135909/115974760-e16e5c80-a513-11eb-82d6-0c2c959a72ec.png)

**Comment by rarafon** [comment]
Text is changed in the select input as well in the Assessments page.
