### ISSUE TITLE
Transfer Summary - # Work Items includes declined items in total.

### ISSUE THREAD

**Issue by JJMilmore** [dandahle/Catalyst-AppVetting#260]
On the Transfer Tab, the "# Work Items" is including the number of declined items in the total.  It should only include the number of items that are approved.  It could be confusing for users to see the total number of items is one number, then click on the Transfer name and see less items to assign to projects.

![Transfer Process](https://user-images.githubusercontent.com/80135909/115975383-3cef1900-a519-11eb-890c-bcbdc8592ee6.png)
![Transfer Summary](https://user-images.githubusercontent.com/80135909/115975384-3e204600-a519-11eb-891c-06773ad3a94f.png)

**Comment by rarafon** [comment]
Correct # of accepted work items should show correctly in the recent commit.
