### ISSUE TITLE
Highlight/Color/Bold - Current Tab selection

### ISSUE THREAD

**Issue by JJMilmore** [dandahle/Catalyst-AppVetting#261]
It would be really helpful for users to quickly look at the top menu and know what Tab they are currently in.  This could be something like changing the Text color to something else, maybe Bolding/Underlining it, or highlight it in some way.

![Tab Highlight](https://user-images.githubusercontent.com/80135909/115975627-26e25800-a51b-11eb-88c1-4e9bd0559474.png)

**Comment by dandahle** [comment]
This is a major usability feature we would like. With so many pages looking similar it takes some effort at times to know what page we are on and what actions to take. Just a highlight or color change, or something similarly distinctive, for the current tab would work.

**Comment by dandahle** [comment]
Additional navigation refinements - for Project and Handle-It pages, add the appropriate title on the page above the tab row and below the Catalyst logo. The two types of pages are nearly identical except for the pdf buttons, so it takes some effort to keep things straight, especially if one steps away from the screen and comes back to resume work.

**Comment by rarafon** [comment]
The navigation link will be highlighted/ white (this is due to how bootstrap sets the nav links as active). Also, I added some titles as well.

**Comment by dandahle** [comment]
Thanks for doing this Andy. This will work for our users.
