### ISSUE TITLE
PAF - formatting and Work Item changes 

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#267]
PAF change requests:

* Reduce the size of Catalyst Letterhead to fit standard 8-1/2 x 11 letter size (or a little smaller). Would like it to take less page real estate.
* delete "Catalyst Partnerships -" immediately under the Catalyst Letterhead (repetitive now with the letterhead)
* delete full materials list per Work Item, and in its place add Cost sub-totals per Work Item

**Comment by rarafon** [comment]
Implemented the changes in the recent commit.  I reduced the letterhead to 400px in width and font size to 12 px when printing..

**Comment by dandahle** [comment]
Looks great, Andy!
