### ISSUE TITLE
Reports edits & corrections

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#271]
The Reports Current Projects tab has two sections, one for Projects and one for Handle-It, however the headings for those sections are reversed. 

Also, since there are now two sections, the column "Handle-It" is no longer needed in the Upcoming Projects tab (however, please do keep that in the .csv export.) 

Completed Projects tab "Total Cost" should be a dollar format. 

For Start Date sorting, please have the oldest / nearest date at the top and the newest / farthest out date at the bottom.

**Comment by rarafon** [comment]
These changes were implemented in the recent commits.

**Comment by dandahle** [comment]
Looks great, Andy!
