### ISSUE TITLE
Vetting Worksheet update stutters

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#279]
Here is what Shawn wrote: "In Vetting, changing the status seems to be weird.  Initially it seems like nothing happens when you try to change the status, but then when you go to a different view and look at the same application it reflects the new status, and when you go back into the vetting view it also has the new status." I noticed this as well. When the status is changed in the Vetting Worksheet, the software seems to hesitate or stutter with the update. The impression is that the status hasn't changed, but when you navigate back to the Vetting Summary page, the Status shows the updated status of the application. I'm wondering if there is some leftover diagnostic code in there somewhere...?

**Comment by rarafon** [comment]
Status wasn't changing for some reason. I've fixed it now.
