### ISSUE TITLE
How to create a user in local system?

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#28]
OK, the good news is I have a local test environment set up that runs. I added an application and verified in RoboMongo that it's there. 

The bad new is somehow I didn't create a user when I set it up, so I can't log in to look around. 

Can anyone help me with how to set up a user in the local system?

**Comment by ironmikesh** [comment]
Go to the CONTRIBUTING.md document on develop.  There should be some helper stuff there...hang on...

* Open `config.js` in text editor or IDE of choice, and follow the instructions given.
* Once you have saved your personal config.js, open a console in the AppVetting root, and 
* Type `node createAdminUser`  
* At this point, you have used the config.js file to connect the MongoDB to the mongo username and password, and you have created a user you will need once we open the app in a browser window.  So, we're all set!

**Comment by dandahle** [comment]
This should be addressed by the new scripting work Rohin did Feb 2020
