### ISSUE TITLE
Remove "Site Comments" from Handle-It projects and PDF

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#280]
Handle-Its bypass the Site Assessment process, so there will not be any comments here. I don't think the field needs to be removed from the database, but it should be removed from the Handle-It PDF and, if possible, from the Handle-It work item in Projects.

**Comment by rarafon** [comment]
It was a remnant from the old handle-it work items that had to be transferred. The work items should be showing any site assessment comments, and I replaced the site comments with project comments for the handle-it work items if there are any.

**Comment by dandahle** [comment]
Very nice, Andy. Thank you!
