### ISSUE TITLE
Modify Checklist in Projects module, under Planning tab

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#282]
In the Projects module, under Planning tab: 
Please replace the item that says "Verify site resources needed” with “Coordinate with Site Host - Sign-in sheets, iPad/phone access for Endis, food & drinks, etc."

Please add an item immediately below it that says “Coordinate with Project Advocate - Specific ministry opportunities with client/volunteers, other needs, pray"

**Comment by rarafon** [comment]
I added the two fields and removed the one for verification. It might require a restart of the database.

**Comment by dandahle** [comment]
Looks good!
