### ISSUE TITLE
Work Items duplicated in Vetting Worksheet

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#285]
In the Roger Stone application (http://18.236.86.81/vettingworksheet/60a55f9a6f6ba448fc471e69) The "Ramp" and "3rd Work Item for Roger" work items are duplicated. 

This also happened with Kris' Kringle Claus for the "Chimney" and "Reindeer Stalls" work items.

**Comment by rarafon** [comment]
They're not duplicated. One is from the assessment and the other is from the project. Does the vetting worksheet view only one type?

**Comment by dandahle** [comment]
The Vetting Worksheet ideally would only keep a record of one Work Item. This will help avoid confusion. If a Work Item is accepted then the Vetting Work Item should be deleted, or just hidden / not shown in the Vetting Worksheet. (I'm guessing I just added complexity to this... :-() 

The purpose is to have a record of what's been asked for in the past and what Catalyst has done with those Work Item requests.

**Comment by rarafon** [comment]
I couldn't think of a good way. What I did instead was add a way to filter out and show only assessment or project work items. Also, it won't be showing work items with the status "accepted" and with the complete or transferred status on the worksheet.

**Comment by dandahle** [comment]
Not sure what's going on here, but the Roger Stone application only shows the Declined Work Items and no Completed Work Items. 

Kris Kringle and Elliott Fremont seem to have the same work items in both Current Work Items and Completed Work Items.

**Comment by rarafon** [comment]
I made some modifications to the worksheet, but I don't believe it has fixed the issue. I haven't been able to reproduce it locally, so I added some console.log statements to debug the work items so that it will show on the instance.

**Comment by dandahle** [comment]
I don't see the duplicate work items now. I will do some more checking on this. 

Do you have access to the EC2 instance at public IP http://18.236.86.81? That is where I am pulling your changes and testing.

**Comment by JJMilmore** [comment]
I cannot replicate this issue, appears to be resolved.
