### ISSUE TITLE
Reorder Vetting Summary buckets - move Transferred above Approved

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#286]
When we convert the existing / old database there will be 200+ applications, most of which will never reach Transferred status. Please move Transferred up in the list since that will be the primary destination for applications and first place to look when clients have repeat requests.

**Comment by rarafon** [comment]
Is this referring to the status bar: 
![image](https://user-images.githubusercontent.com/11997170/119242527-62207880-bb13-11eb-8a37-9c5bd8c2efcb.png)
or the /view page
![image](https://user-images.githubusercontent.com/11997170/119242540-749ab200-bb13-11eb-834e-73a3212699d9.png)
or both? Also, what place should it have?

**Comment by dandahle** [comment]
Thanks for asking, Andy. No, that is issue #224. :-) 

this refers to the order in the Vetting Summary page
![Screenshot 2021-05-23 072126-vettingsummary](https://user-images.githubusercontent.com/6306417/119264416-f3d1c980-bb97-11eb-8ab3-3ccd13c6f9d6.png)

**Comment by rarafon** [comment]
The transferred section was moved.
