### ISSUE TITLE
Add link to Application in Project Info side bar

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#287]
It would be really convenient if there is a link to the application in the Project page in the Info Application tab on the right side bar.

**Comment by rarafon** [comment]
The link was added in the recent commit. It'll only show the application name as a link to the page when the user has the "VET" user role.

**Comment by dandahle** [comment]
Thanks Andy, you are awesome! 

I’ve been moving all week and still not done, but I will make some time tomorrow to pull the updates and restart the server. I will look at #285 more closely, too, to see if I can provide better input to you on what leads up to the issue. 

Thank you! 

==> Dan

**Comment by dandahle** [comment]
Works awesome, Andy! thank you :-)
