### ISSUE TITLE
Add Previous Applicant option to Application

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#296]
Now that we can have multiple projects per applicant, we should add an option in the online application for people who have filled out an application for help from Catalyst in the past. We can add an additional question in the very front when we ask if people own their own home and are current on their mortgage payments. With that we can just have them enter their name and address along with what new work on their house they would like help with. This should show up in the "New Applications" section of the Vetting page, or maybe add a "Returning Applicants" section, where we can find their existing application, add the new work requested and update the vetting process to Phone Call Needed and determine appropriate steps for their situation, e.g. Approved == verify key data, Withdrawn / Declined == Awaiting Documents, etc.

**Comment by CatalystNW** [comment]
moved to new GitHub
