### ISSUE TITLE
Add “Withdrawn - ooa” to application status

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#37]
Add “Withdrawn - ooa” status to identify applications declined because they are out of our service area (ooa == out of area). Could be linked or triggered by Application question “Inside service area?”

**Comment by ironmikesh** [comment]
Using branch APP-37 for tracking

**Comment by ironmikesh** [comment]
Added Withdrawn - out of area to application status list.
Verified withdrawnooa was in database
Added withdrawnooa to vetting home page so it is listed with the withdrawn applications
