### ISSUE TITLE
VW - Instructions for Vetting Summary

### ISSUE THREAD

**Issue by ironmikesh** [dandahle/Catalyst-AppVetting#39]
Provide instructions for vetting summary so vetting agent knows that stuff written in that box will be seen by the Site Assessors - so they should provide helpful information for site assessors...

[Dan, if you want to provide actual verbage, feel free to do so here]

**Comment by ironmikesh** [comment]
Beginning work on this

**Comment by dandahle** [comment]
suggested verbiage (although long, let's start here and pare back): 
This Vetting Summary appears in the Site Assessment view. Please provide public information here that will provide useful context and background to the Site Assessors when they visit the client's home. (DO NOT provide private (e.g. specific health and/or financial) information). Note that Work Items will also be visible in the Site Assessment view.

**Comment by ironmikesh** [comment]
Text used;
_Information provided here will be visible to Site Assessors, and should give useful context for when they visit the client's home.  (DO NOT provide private (e.g. specific health and/or financial) information._

Also for Site Assessment explanation:
_Look for messages, if any, from Site Assessors in the area below.  Site Assessors have provided this to the Vetting Agents for potential follow-up with the client._
