### ISSUE TITLE
Add "Staff Assigned" elements

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#54]
Add the Catalyst Staff person assigned to vet the application. 

For the Application the staff assigned is the Vetting Agent. Note that this can be from a pull down list of registered users with a Vetting Role since the vetting agent will be someone given a login and Vetting Agent role for the AppVetting tool. Add column in Vetting Summary showing assigned staff (similar to what was done in Project Summary).

**Comment by dandahle** [comment]
Upgrading priority. With more staff involved, being able to directly track who is vetting an application is now required.

**Comment by CatalystNW** [comment]
Migrating to new GitHub
