### ISSUE TITLE
Add Wrap Up tab in Tasks summary page

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#66]
Add a third tab to the Tasks page showing the open assigned tasks for wrapping up a project from the Wrap Up tab in the Project View page. This should be similar / the same treatment as used for the Planning Tasks on the Planning tab. 

Nice to have: Wrap up tasks with the owner assigned to the logged in user also show up in the My Tasks tab.

**Comment by dandahle** [comment]
Andy, I hope you will look into this and figure out a way to implement it. The Task Tracker is very useful, and we would like to extend it to track the tasks to wrap up a project. I don't know what's involved, but if you find it easier to re-write the Task Tracker function that is likely OK.

**Comment by CatalystNW** [comment]
Moved to new GitHub
