### ISSUE TITLE
Add commented code to direct backups to appropriate S3 buckets

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#73]
Determine access privileges for S3 bucket to be used for develop and prototype branches. 

Add code in db_backup.sh script to point to the appropriate bucket for back up depending on whether it is being installed in the develop instance, the prototype instance or the production instance. Comment all three options, and after the code is updated edit the db_backup.sh script to use the bucket appropriate to the instance. Before this enhancement is implemented the default is backup for production. 

Also, update the Readme files to note the changes needed for backups to happen properly.

**Comment by rohinadalja** [comment]
db_backup.sh = Production use
NEW:  db_backup_develop.sh = Development use (same with restore)
