### ISSUE TITLE
Fix Empty Tasks bug

### ISSUE THREAD

**Issue by rohinadalja** [dandahle/Catalyst-AppVetting#82]
As described in email

**Comment by dandahle** [comment]
Using his Mac with Safari, Dan went through a number of applications that are completed projects and ticked the “completed” boxes for each of the planning tasks. However, they still show up in the Tasks list with 3 Empty entries in the Hot Tasks lists. For the Elvander application he went through renaming 2 custom task lists but there was no change in the Tasks Hot List entries. Even after renaming the Task Description to "1st custom task" and "2nd custom task" only "Empty" showed up in Hot Tasks.
