### ISSUE TITLE
Add Application “Comments” field & column 

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#92]
Shawn **really** wants a field to capture shorthand descriptions of the applications and/or their situation which are memorable (sometimes silly) to help the him and the office personnel keep straight all the different applications that come in. 

Requires a new field restricted to Vetting Agents for viewing. And, display new field column in the Vetting Summary. Because this new field may contain personal info for the client, it should be ONLY visible in the vetting views.

**Comment by CatalystNW** [comment]
Moved to new GitHub
