### ISSUE TITLE
Add Catalyst footer to PAF and Handle-It PDFs

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#93]
Add Catalyst info in footer along with required and desired disclaimers to the footer of the exported PDF. 

Dan to Verify with Shwan the needed language to add.

**Comment by dandahle** [comment]
Is this still needed after Andy updated the Handle-It report and PAF?

**Comment by CatalystNW** [comment]
Moved to new GitHub
