### ISSUE TITLE
Description field for "Other Help Requested" not visible

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#95]
In the Vetting Application View and the Vetting Worksheet View The true / false tick box for Other Help Requested appears and works properly; however, when it the box is ticked for Yes or true, the field with the description of the help requested should show up, but does not. 

Resolution: fix code to show the Other Help Requested description field appears.

**Comment by rohinadalja** [comment]
I don't recollect where we are storing that? Is it during the application form fill up? I cannot find this field, I can only find the true/false field

**Comment by dandahle** [comment]
This field shows up and can be populated in the Client Application after the "Have you already requested help from other Non-Profits, from your City, from your County, or other Organization?" tick box / radio button is clicked Yes. This is immediately before the Property Information section.

**Comment by dandahle** [comment]
The field is in documentPackage.js lines 156-160. It needs to display in the Application View and Vetting Worksheet immediately after the tick box is displayed.

**Comment by ironmikesh** [comment]
I have fixed this issue.

Highlights:
* The requested other help is now visible on both application view and vetting worksheet.
* They are editable inline on both pages
* Tested both in local and they both appear and are editable and changes reflect in database and persist on the screen.

**Comment by dandahle** [comment]
QA tested in develop then pushed to master and pulled into production.
