### ISSUE TITLE
using iPad Project Status not updatable

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#96]
Using an iPad when opening the Project (clicking on it in the Project Summary) the Project opens with all the tabs visible, but there is no viewable field for "Status" so it cannot be updated. The field does appear and can be updated/modified using Chrome on a Mac.

**Comment by dandahle** [comment]
Changing this to Priority 1 because a number of Catalyst staffers use iPad regularly.

**Comment by CatalystNW** [comment]
Fixed for now.
